DROP DATABASE SpMedGroupM;

CREATE DATABASE SpMedGroupM;

USE SpMedGroupM;

CREATE TABLE Generos(
IdGenero INT PRIMARY KEY IDENTITY, 	
Genero VARCHAR(200) NOT NULL
);
GO



CREATE TABLE Situacoes(
IdSituacao INT PRIMARY KEY IDENTITY, 	
Situacao VARCHAR(200) NOT NULL
);
GO



CREATE TABLE PlanoSaude(
IdPlanoSaude INT PRIMARY KEY IDENTITY, 	
NomePlano VARCHAR(255) NOT NULL
);

GO



CREATE TABLE Estados(
IdEstado INT PRIMARY KEY IDENTITY, 	
Estado VARCHAR(255) NOT NULL,
Capital VARCHAR(255) NOT NULL,
Sigla VARCHAR(255) NOT NULL
);
GO

CREATE TABLE Cidades(
IdCidade INT PRIMARY KEY IDENTITY, 	
Cidade VARCHAR(255) NOT NULL,
IdEstado INT FOREIGN KEY REFERENCES Estados(IdEstado) NOT NULL
);
GO


CREATE TABLE Bairros(
IdBairro INT PRIMARY KEY IDENTITY, 	
Bairro VARCHAR(255) NOT NULL
);
GO


CREATE TABLE Ceps(
IdCep INT PRIMARY KEY IDENTITY, 	
Cep VARCHAR(10) NOT NULL,
IdBairro INT FOREIGN KEY REFERENCES Bairros(IdBairro) NOT NULL,
IdCidade INT FOREIGN KEY REFERENCES Cidades(IdCidade) NOT NULL);
GO
 


CREATE TABLE Enderecos(
IdEndereco INT PRIMARY KEY IDENTITY, 	
Logradouro VARCHAR(255) NOT NULL,
Numero VARCHAR(10) NOT NULL,
Complemento VARCHAR(255),
IdCep INT FOREIGN KEY REFERENCES Ceps(IdCep) NOT NULL
);
GO




CREATE TABLE Clinicas(
IdClinica INT PRIMARY KEY IDENTITY, 	
CNPJ VARCHAR(14) NOT NULL,
NomeFantasia  VARCHAR(255) NOT NULL,	
RazaoSocial	 VARCHAR(255) NOT NULL,
Telefone VARCHAR(16) NOT NULL,
HorarioAbertura Time NOT NULL,
HorarioFechamento Time NOT NULL,
IdEndereco INT FOREIGN KEY REFERENCES Enderecos(IdEndereco) NOT NULL
);

GO

CREATE TABLE TipoEspecialidade(
IdTipoEspecialidade INT PRIMARY KEY IDENTITY, 	
NomeEspecialidade VARCHAR(255) NOT NULL
);

GO

CREATE TABLE TipoUsuario(
IdTipoUsuario INT PRIMARY KEY IDENTITY, 	
Tipo VARCHAR(100) NOT NULL
);

GO


CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY,
NomeUsuario VARCHAR(255) NOT NULL,
Email VARCHAR(100) NOT NULL,	
Senha VARCHAR(255) NOT NULL,
DataNascimento	Date NOT NULL,
Telefone VARCHAR(16) NOT NULL,
Telefone2 VARCHAR(16), 
RG	VARCHAR(14) NOT NULL,
Cpf	VARCHAR(14) NOT NULL,
IdGenero INT FOREIGN KEY REFERENCES Generos(IdGenero) NOT NULL,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
IdEndereco INT FOREIGN KEY REFERENCES Enderecos(IdEndereco) NOT NULL
);

GO

CREATE TABLE Medicos(
IdMedico INT PRIMARY KEY IDENTITY, 	
CRM VARCHAR(14) NOT NULL,
IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario) NOT NULL,
IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica) NOT NULL
);
GO

CREATE TABLE EspecialidadeMedico(
IdEspecialidadeMedico INT PRIMARY KEY IDENTITY, 	
IdTipoEspecialidade INT FOREIGN KEY REFERENCES TipoEspecialidade(IdTipoEspecialidade) NOT NULL,
IdMedico INT FOREIGN KEY REFERENCES Medicos(IdMedico) NOT NULL
);
GO


CREATE TABLE Consultas(
IdConsulta INT PRIMARY KEY IDENTITY,
DataConsulta DateTime2 NOT NULL, 	
ValorConsulta DECIMAL,
Descricao VARCHAR(255),
IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario) NOT NULL,
IdPlanoSaude INT FOREIGN KEY REFERENCES PlanoSaude(IdPlanoSaude) NOT NULL,
IdSituacao INT FOREIGN KEY REFERENCES Situacoes(IdSituacao) NOT NULL,
IdMedico INT FOREIGN KEY REFERENCES Medicos(IdMedico) NOT NULL
);
GO